name: Deploy to VPS (quintomolinillo)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-quintomolinillo
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key & config
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          # Llave privada
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Conocidos + config para usar SOLO esta llave
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true
          cat > ~/.ssh/config <<EOF
          Host vps
            HostName ${{
              secrets.SSH_HOST
            }}
            User ${{
              secrets.SSH_USER
            }}
            Port ${{
              secrets.SSH_PORT
            }}
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes
            PreferredAuthentications publickey
            StrictHostKeyChecking yes
          EOF

      - name: Deploy via rsync
        shell: bash
        run: |
          rsync -avr \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".DS_Store" \
            ./ vps:${{ secrets.SSH_TARGET }}/

      - name: Post-deploy (opcional: normaliza permisos)
        if: always()
        shell: bash
        run: |
          ssh vps "find '${{ secrets.SSH_TARGET }}' -type d -exec chmod 755 {} \; && find '${{ secrets.SSH_TARGET }}' -type f -exec chmod 644 {} \;"